apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          # ATTENTION : Utiliser le placeholder FULL TAG pour pointer vers le registre distant
          image: {{IMAGE_FULL_TAG}} 
          # Conservez IfNotPresent ou passez à Always (recommandé pour SHA unique)
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: {{CONTAINER_PORT}}
      
      # OBLIGATOIRE : Réfèrence au secret 'regcred' créé par le workflow 
      # pour permettre à Minikube de s'authentifier et de tirer l'image depuis Docker Hub.
      imagePullSecrets:
        - name: regcred
