# my-app-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  namespace: {{NAMESPACE}}
  annotations:
    # Important: Ensure this matches the ingressClass if you customized it
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true" # Rewrite target as /
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # Rewrite target as /
spec:
  ingressClassName: nginx
  rules:
  # Not host also means allow IP adress
  #- host: # Leave blank so that it is accessible through IP address
    - http:
        paths:
        - path: /{{APP_ROUTE}}(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{APP_NAME}}-service # Your application's internal service
              port:
                number: {{SERVICE_PORT}} # The port your application service exposes