apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  selector:
    app: {{APP_NAME}}
  ports:
    - protocol: TCP
      port: {{SERVICE_PORT}}
      targetPort: {{CONTAINER_PORT}}
      name: web
  type: ClusterIP